{
 "title": "Taipower Watch (InfluxDB)",
 "tags": [ "influxdb" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "網站聲明",
   "type": "text",
   "options": {
    "content": "<ul>\n    <li>本站非台灣電力公司官方網站</li>\n    <li>數據來源 <a href=\"https://data.gov.tw/dataset/8931\" target=\"_blank\">經濟部主題式開放資料服務</a></li>\n</ul>"
   }
  },
  {
   "title": "總發電量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "Total",
     "rawSql": "SELECT time, total_net_generation AS \"Total\" FROM taipower_energy_total WHERE $__timeFilter(time) ORDER BY time"
    },
    {
     "legendFormat": "Pre24H",
     "rawSql": "SELECT time + INTERVAL '1 day' AS time, total_net_generation AS \"Pre24H\" FROM taipower_energy_total WHERE time >= $__timeFrom - INTERVAL '1 day' AND time <= $__timeTo - INTERVAL '1 day' ORDER BY time"
    }
   ]
  },
  {
   "title": "即時總發電量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, total_net_generation AS \"Total\" FROM taipower_energy_total WHERE $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "核能",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'nuclear' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "燃煤",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'coal' AND $__timeFilter(time) ORDER BY time"
    },
    {
     "legendFormat": "{{unit}}-ipp",
     "rawSql": "SELECT time, unit || '-ipp' AS unit, net_generation FROM taipower_energy WHERE energy_type = 'ipp_coal' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "天然氣",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'lng' AND $__timeFilter(time) ORDER BY time"
    },
    {
     "legendFormat": "{{unit}}-ipp",
     "rawSql": "SELECT time, unit || '-ipp' AS unit, net_generation FROM taipower_energy WHERE energy_type = 'ipp_lng' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "太陽能",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'solar' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "風力",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'wind' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "汽電共生",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'co_gen' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "燃油",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'fuel_oil' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "輕油",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'diesel' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "水力",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'hydro' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "儲能/儲能負載",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}儲能",
     "rawSql": "SELECT time, unit || '儲能' AS unit, net_generation FROM taipower_energy WHERE energy_type = 'storage' AND $__timeFilter(time) ORDER BY time"
    },
    {
     "legendFormat": "{{unit}}負載",
     "rawSql": "SELECT time, unit || '負載' AS unit, net_generation FROM taipower_energy WHERE energy_type = 'energy_storage_system_load' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "其它再生能源",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "legendFormat": "{{unit}}",
     "rawSql": "SELECT time, unit, net_generation FROM taipower_energy WHERE energy_type = 'other_renewable_energy' AND $__timeFilter(time) ORDER BY time"
    }
   ]
  }
 ]
}